export const data = [
  {
    key: "1",
    service: "Удирдлагын алба",
    branch: "Салбар 1",
    normType: "Норм 1",
    subClass: "Ангилал A",
    smallClass: "Бага ангилал 1",
    repairType: "Засварын төрөл X",
    group: "Групп I",
    addition: "Нэмэлт мэдээлэл 1",
    unit: "ш",
    number: 10,
  },
  {
    key: "2",
    service: "Санхүүгийн алба",
    branch: "Салбар 2",
    normType: "Норм 2",
    subClass: "Ангилал B",
    smallClass: "Бага ангилал 2",
    repairType: "Засварын төрөл Y",
    group: "Групп II",
    addition: "Нэмэлт мэдээлэл 2",
    unit: "кг",
    number: 20,
  },
  {
    key: "3",
    service: "Маркетингийн алба",
    branch: "Салбар 3",
    normType: "Норм 3",
    subClass: "Ангилал C",
    smallClass: "Бага ангилал 3",
    repairType: "Засварын төрөл Z",
    group: "Групп III",
    addition: "Нэмэлт мэдээлэл 3",
    unit: "л",
    number: 15,
  },
  // Add more data as needed
];
